# Generated by Django 4.0.4 on 2022-04-14 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0029_auto_20210415_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 19, 49, 4, 424801), null=True),
        ),
    ]
